/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SosRouteImport } from './routes/sos'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MapRouteImport } from './routes/map'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoadsIndexRouteImport } from './routes/roads.index'
import { Route as RoadsQueueRouteImport } from './routes/roads.queue'
import { Route as RoadsEmergencyRouteImport } from './routes/roads.emergency'
import { Route as RoadsArchitectureRouteImport } from './routes/roads.architecture'

const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsIndexRoute = RoadsIndexRouteImport.update({
  id: '/roads/',
  path: '/roads/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsQueueRoute = RoadsQueueRouteImport.update({
  id: '/roads/queue',
  path: '/roads/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsEmergencyRoute = RoadsEmergencyRouteImport.update({
  id: '/roads/emergency',
  path: '/roads/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsArchitectureRoute = RoadsArchitectureRouteImport.update({
  id: '/roads/architecture',
  path: '/roads/architecture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/routes': typeof RoutesRoute
  '/sos': typeof SosRoute
  '/roads/architecture': typeof RoadsArchitectureRoute
  '/roads/emergency': typeof RoadsEmergencyRoute
  '/roads/queue': typeof RoadsQueueRoute
  '/roads/': typeof RoadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/routes': typeof RoutesRoute
  '/sos': typeof SosRoute
  '/roads/architecture': typeof RoadsArchitectureRoute
  '/roads/emergency': typeof RoadsEmergencyRoute
  '/roads/queue': typeof RoadsQueueRoute
  '/roads': typeof RoadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/routes': typeof RoutesRoute
  '/sos': typeof SosRoute
  '/roads/architecture': typeof RoadsArchitectureRoute
  '/roads/emergency': typeof RoadsEmergencyRoute
  '/roads/queue': typeof RoadsQueueRoute
  '/roads/': typeof RoadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/map'
    | '/reports'
    | '/routes'
    | '/sos'
    | '/roads/architecture'
    | '/roads/emergency'
    | '/roads/queue'
    | '/roads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/map'
    | '/reports'
    | '/routes'
    | '/sos'
    | '/roads/architecture'
    | '/roads/emergency'
    | '/roads/queue'
    | '/roads'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/map'
    | '/reports'
    | '/routes'
    | '/sos'
    | '/roads/architecture'
    | '/roads/emergency'
    | '/roads/queue'
    | '/roads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  MapRoute: typeof MapRoute
  ReportsRoute: typeof ReportsRoute
  RoutesRoute: typeof RoutesRoute
  SosRoute: typeof SosRoute
  RoadsArchitectureRoute: typeof RoadsArchitectureRoute
  RoadsEmergencyRoute: typeof RoadsEmergencyRoute
  RoadsQueueRoute: typeof RoadsQueueRoute
  RoadsIndexRoute: typeof RoadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads/': {
      id: '/roads/'
      path: '/roads'
      fullPath: '/roads/'
      preLoaderRoute: typeof RoadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads/queue': {
      id: '/roads/queue'
      path: '/roads/queue'
      fullPath: '/roads/queue'
      preLoaderRoute: typeof RoadsQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads/emergency': {
      id: '/roads/emergency'
      path: '/roads/emergency'
      fullPath: '/roads/emergency'
      preLoaderRoute: typeof RoadsEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads/architecture': {
      id: '/roads/architecture'
      path: '/roads/architecture'
      fullPath: '/roads/architecture'
      preLoaderRoute: typeof RoadsArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  MapRoute: MapRoute,
  ReportsRoute: ReportsRoute,
  RoutesRoute: RoutesRoute,
  SosRoute: SosRoute,
  RoadsArchitectureRoute: RoadsArchitectureRoute,
  RoadsEmergencyRoute: RoadsEmergencyRoute,
  RoadsQueueRoute: RoadsQueueRoute,
  RoadsIndexRoute: RoadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
